/**
 * Indian financial year: 1 April – 31 March.
 *
 * MUST stay identical to public.fy_code(date) in migration 01 — LR numbers are
 * generated by the database and displayed by this. A test asserts both agree.
 */
export function financialYearCode(date: Date): string {
  const year = date.getFullYear();
  const month = date.getMonth() + 1; // 1-12
  const startYear = month >= 4 ? year : year - 1;
  const a = String(startYear % 100).padStart(2, "0");
  const b = String((startYear + 1) % 100).padStart(2, "0");
  return `${a}${b}`;
}

/** Human form: '2627' → '2026-27'. */
export function financialYearLabel(code: string): string {
  if (!/^[0-9]{4}$/.test(code)) throw new Error(`financialYearLabel: bad code '${code}'`);
  const a = Number(code.slice(0, 2));
  const century = a >= 70 ? 1900 : 2000; // fleet records do not predate 1970
  return `${century + a}-${code.slice(2)}`;
}
